name: Actions
on:
  repository_dispatch:
    types: [actions-command]
jobs:
  help:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ¤– Bot comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: laugh
          body: |
            #### ðŸ“– Commands on ChatOps
            > | Command              | Description
            > | -------------------- | -------------------------------------------- 
            > | `/provision app_id=` | Provision infrastructure on an environment specified.
