name: "ChatOps"
on:
  issue_comment:
    types: [created]

jobs:
  chatops:
    runs-on: ubuntu-latest
    outputs:
      feature: ${{ steps.feature.outputs.BOOL_TRIGGERED }}
#      development: ${{ steps.development.outputs.BOOL_TRIGGERED }}
    steps:
      - name: ğŸ· Provision on feature environment
        uses: machine-learning-apps/actions-chatops@master
        id: feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TRIGGER_PHRASE: ".provision"

#      - name: ğŸ· Provision on development environment
#        uses: machine-learning-apps/actions-chatops@master
#        id: development
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          TRIGGER_PHRASE: ".provision development"

  outputs:
    needs:
      - chatops
    runs-on: ubuntu-latest
    steps:
      - run: echo feature=${{ needs.chatops.outputs.feature }}

  feature:
    needs:
      - chatops
    if: ${{ needs.chatops.outputs.feature == 'true' }}
    runs-on: ubuntu-latest
    #    environment: feature
    steps:
      - name: ğŸ‘‹ Hello Response
        uses: NejcZdovc/comment-pr@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          message: "Hello feature ğŸ‘‹"

#  development:
#    needs:
#      - chatops
#    if: ${{ needs.chatops.outputs.development == 'true' }}
#    runs-on: ubuntu-latest
#    #    environment: feature
#    steps:
#      - name: ğŸ‘‹ Hello Response
#        uses: NejcZdovc/comment-pr@v1
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        with:
#          message: "Hello development ğŸ‘‹"