name: "ChatOps"
on:
  issue_comment:
    types: [created]

jobs:
  chatops:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        env: # required
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TRIGGER_PHRASE: "/deploy"
        id: prcomm

      - name: ğŸ‘‹ Hello Response
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: NejcZdovc/comment-pr@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          message: "Hello world ğŸ‘‹"

#      - name: ğŸ· Provision on development environment
#        uses: machine-learning-apps/actions-chatops@master
#        id: development
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          TRIGGER_PHRASE: ".provision development"

#  development:
#    needs:
#      - chatops
#    if: ${{ needs.chatops.outputs.development == 'true' }}
#    runs-on: ubuntu-latest
#    #    environment: feature
#    steps:
#      - name: ğŸ‘‹ Hello Response
#        uses: NejcZdovc/comment-pr@v1
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        with:
#          message: "Hello development ğŸ‘‹"